runtime: nodejs
env: flex
beta_settings:
  cloud_sql_instances: "probot-memory:us-east1:probot-business-mapping"
# env_variables:
#   INSTANCE_CONNECTION_NAME: "probot-memory:us-east1:probot-business-mapping"